<?php declare(strict_types=1);

namespace StellarWP\Foundation\Database\Query;

use DateTimeInterface;
use Doctrine\DBAL\ArrayParameterType;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Exception;
use Doctrine\DBAL\ParameterType;
use Doctrine\DBAL\Types\Type;
use InvalidArgumentException;
use StellarWP\Foundation\Database\Query\ValueObjects\Fragment;
use StellarWP\Foundation\Database\Query\ValueObjects\ParameterSet;

/**
 * Executes compiled and application-owned SQL through the shared connection.
 *
 * @internal
 */
final readonly class Executor
{
	/**
	 * Use the application's existing managed connection.
	 */
	public function __construct(
		private Connection $connection,
	) {
	}

	/**
	 * Fetch all result rows as associative arrays.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 *
	 * @return list<array<string, mixed>>
	 */
	public function rows(Fragment $statement): array {
		return $this->fetchAllAssociative($statement->sql, $statement->bindings);
	}

	/**
	 * Fetch the first column of every result row without converting values.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 *
	 * @return list<mixed>
	 */
	public function column(Fragment $statement): array {
		$parameters = $this->parameters($statement->bindings);

		return $this->connection->fetchFirstColumn($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Fetch the first row, or false when no row matches.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 *
	 * @return array<string, mixed>|false
	 */
	public function first(Fragment $statement): array|false {
		$parameters = $this->parameters($statement->bindings);

		return $this->connection->fetchAssociative($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Fetch the first column, preserving DBAL's false result for no row.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 */
	public function value(Fragment $statement): mixed {
		$parameters = $this->parameters($statement->bindings);

		return $this->connection->fetchOne($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Execute a write and preserve DBAL's affected-row count.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 */
	public function statement(Fragment $statement): int|string {
		return $this->executeStatement($statement->sql, $statement->bindings);
	}

	/**
	 * Fetch associative rows with inferred types and optional explicit conversions.
	 *
	 * @param list<mixed>|array<string, mixed>                                        $bindings
	 * @param array<int<0, max>|string, string|Type|ParameterType|ArrayParameterType> $types
	 *
	 * @throws InvalidArgumentException For unsupported values without an explicit type.
	 * @throws Exception                When execution, type conversion, or fetching fails.
	 *
	 * @return list<array<string, mixed>>
	 */
	public function fetchAllAssociative(string $sql, array $bindings = [], array $types = []): array {
		$parameters = $this->parameters($bindings, $types);

		return $this->connection->fetchAllAssociative($sql, $parameters->values, $parameters->types);
	}

	/**
	 * Execute SQL with inferred types unless the caller supplies an explicit type.
	 *
	 * @param list<mixed>|array<string, mixed>                                        $bindings
	 * @param array<int<0, max>|string, string|Type|ParameterType|ArrayParameterType> $types
	 *
	 * @throws InvalidArgumentException For unsupported values without an explicit type.
	 * @throws Exception                When execution or type conversion fails.
	 */
	public function executeStatement(string $sql, array $bindings = [], array $types = []): int|string {
		$parameters = $this->parameters($bindings, $types);

		return $this->connection->executeStatement($sql, $parameters->values, $parameters->types);
	}

	/**
	 * Read the identifier generated by the immediately preceding single-row insert.
	 *
	 * @throws Exception When no generated identifier is available or the connection fails.
	 */
	public function lastInsertId(): int|string {
		return $this->connection->lastInsertId();
	}

	/**
	 * Normalize a bound value without accessing the database.
	 *
	 * Dates retain their timezone's wall time and microseconds. Pass decimal strings
	 * for exact values; floating-point values use PHP's string conversion.
	 *
	 * @throws InvalidArgumentException For arrays, resources, or unsupported objects.
	 */
	public function normalize(mixed $value): int|string|null {
		if ($value instanceof DateTimeInterface) {
			return $value->format('Y-m-d H:i:s.u');
		}

		if (is_bool($value)) {
			return (int) $value;
		}

		if (is_float($value)) {
			return (string) $value;
		}

		if ($value === null || is_int($value) || is_string($value)) {
			return $value;
		}

		throw new InvalidArgumentException('Unsupported query value: ' . get_debug_type($value) . '.');
	}

	/**
	 * Prepare values and explicit binding types for one execution.
	 *
	 * @param list<mixed>|array<string, mixed>                                        $bindings
	 * @param array<int<0, max>|string, string|Type|ParameterType|ArrayParameterType> $types
	 */
	private function parameters(array $bindings, array $types = []): ParameterSet {
		foreach ($bindings as $key => $value) {
			if (array_key_exists($key, $types)) {
				continue;
			}

			$value          = $this->normalize($value);
			$bindings[$key] = $value;
			$types[$key]    = match (true) {
				$value === null => ParameterType::NULL,
				is_int($value)  => ParameterType::INTEGER,
				default         => ParameterType::STRING,
			};
		}

		return new ParameterSet($bindings, $types);
	}
}
