<?php declare(strict_types=1);

namespace StellarWP\Foundation\Database\Query;

use DateTimeInterface;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Exception;
use Doctrine\DBAL\ParameterType;
use InvalidArgumentException;
use StellarWP\Foundation\Database\Query\ValueObjects\Fragment;
use StellarWP\Foundation\Database\Query\ValueObjects\ParameterSet;

/**
 * Executes compiled statements through the application's shared connection.
 *
 * @internal
 */
final readonly class Executor
{
	/**
	 * Use the application's existing managed connection.
	 */
	public function __construct(
		private Connection $connection,
	) {
	}

	/**
	 * Fetch all result rows as associative arrays.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 *
	 * @return list<array<string, mixed>>
	 */
	public function rows(Fragment $statement): array {
		$parameters = $this->parameters($statement);

		return $this->connection->fetchAllAssociative($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Fetch the first row, or false when no row matches.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 *
	 * @return array<string, mixed>|false
	 */
	public function first(Fragment $statement): array|false {
		$parameters = $this->parameters($statement);

		return $this->connection->fetchAssociative($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Fetch the first column, preserving DBAL's false result for no row.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 */
	public function value(Fragment $statement): mixed {
		$parameters = $this->parameters($statement);

		return $this->connection->fetchOne($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Execute a write and preserve DBAL's affected-row count.
	 *
	 * @throws InvalidArgumentException For unsupported bound values.
	 * @throws Exception                When execution fails.
	 */
	public function statement(Fragment $statement): int|string {
		$parameters = $this->parameters($statement);

		return $this->connection->executeStatement($statement->sql, $parameters->values, $parameters->types);
	}

	/**
	 * Read the identifier generated by the immediately preceding single-row insert.
	 *
	 * @throws Exception When no generated identifier is available or the connection fails.
	 */
	public function lastInsertId(): int|string {
		return $this->connection->lastInsertId();
	}

	/**
	 * Normalize a bound value without accessing the database.
	 *
	 * Dates retain their timezone's wall time and microseconds. Pass decimal strings
	 * for exact values; floating-point values use PHP's string conversion.
	 *
	 * @throws InvalidArgumentException For arrays, resources, or unsupported objects.
	 */
	public function normalize(mixed $value): int|string|null {
		if ($value instanceof DateTimeInterface) {
			return $value->format('Y-m-d H:i:s.u');
		}

		if (is_bool($value)) {
			return (int) $value;
		}

		if (is_float($value)) {
			return (string) $value;
		}

		if ($value === null || is_int($value) || is_string($value)) {
			return $value;
		}

		throw new InvalidArgumentException('Unsupported query value: ' . get_debug_type($value) . '.');
	}

	/**
	 * Prepare values and explicit binding types for one execution.
	 */
	private function parameters(Fragment $statement): ParameterSet {
		$bindings = [];
		$types    = [];

		foreach ($statement->bindings as $value) {
			$value      = $this->normalize($value);
			$bindings[] = $value;
			$types[]    = match (true) {
				$value === null => ParameterType::NULL,
				is_int($value)  => ParameterType::INTEGER,
				default         => ParameterType::STRING,
			};
		}

		return new ParameterSet($bindings, $types);
	}
}
