<?php declare(strict_types=1);

namespace StellarWP\Foundation\Cli\Generation\Php;

use PhpParser\Error;
use PhpParser\Lexer;
use PhpParser\Node;
use PhpParser\Node\Expr;
use PhpParser\Node\Stmt;
use PhpParser\Node\UseItem;
use PhpParser\NodeFinder;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitor\NameResolver;
use PhpParser\ParserFactory;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\LineComment;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\LineInsertion;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\MergeArrayVarTarget;

/**
 * Performs small, parser-aware edits to PHP source files generated by Foundation.
 */
final readonly class PhpSourceEditor
{
	/**
	 * Create an editor with PHP-Parser services for syntax trees and source-position tokens.
	 */
	public function __construct(
		private ParserFactory $parserFactory,
		private Lexer $lexer
	) {
	}

	/**
	 * Determine whether the supplied source is syntactically valid PHP.
	 */
	public function canParse(string $contents): bool {
		return $this->parse($contents) !== null;
	}

	/**
	 * Determine whether a class is already imported under its default short name.
	 *
	 * For example, `Acme\Reports\Table` matches `use Acme\Reports\Table;` but
	 * does not match an import of the same class aliased as another name.
	 */
	public function hasImport(string $contents, string $fullyQualifiedClass): bool {
		$target = trim($fullyQualifiedClass, '\\');
		$alias  = basename(str_replace('\\', '/', $target));

		foreach ($this->imports($contents) as $import) {
			if (strcasecmp($import['class'], $target) === 0 && strcasecmp($import['alias'], $alias) === 0) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Determine whether a proposed short name conflicts with another import or class declaration.
	 *
	 * For example, generating `ReportsTable` conflicts with
	 * `use Other\Package\ReportsTable;` and `final class ReportsTable`.
	 */
	public function hasImportShortNameCollision(string $contents, string $class, string $fullyQualifiedClass): bool {
		$target = trim($fullyQualifiedClass, '\\');

		foreach ($this->imports($contents) as $import) {
			if (strcasecmp($import['alias'], $class) === 0 && strcasecmp($import['class'], $target) !== 0) {
				return true;
			}
		}

		$statements = $this->parse($contents);

		if ($statements === null) {
			return false;
		}

		foreach ($this->topLevelStatements($statements) as $statement) {
			if ($statement instanceof Stmt\ClassLike && $statement->name !== null && strcasecmp($statement->name->toString(), $class) === 0) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Return the first class-like declaration or import alias that conflicts in PHP's case-insensitive symbol table.
	 *
	 * This detects invalid generated files such as importing `Migration` and
	 * declaring a class named `migration` in the same namespace.
	 */
	public function classImportCollision(string $contents): ?string {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return null;
		}

		$aliases = [];

		foreach ($this->imports($contents) as $import) {
			$alias = strtolower($import['alias']);

			if (isset($aliases[$alias])) {
				return $import['alias'];
			}

			$aliases[$alias] = $import['class'];
		}

		foreach ($this->topLevelStatements($statements) as $statement) {
			if (! $statement instanceof Stmt\ClassLike || $statement->name === null) {
				continue;
			}

			$name = $statement->name->toString();
			$key  = strtolower($name);

			if (isset($aliases[$key])) {
				return $name;
			}

			$aliases[$key] = $name;
		}

		return null;
	}

	/**
	 * Determine whether the source contains an exact standalone line comment.
	 *
	 * Marker text embedded in code or a longer comment is intentionally ignored.
	 */
	public function hasLineComment(string $contents, string $comment): bool {
		return $this->lineComment($contents, $comment) !== null;
	}

	/**
	 * Add a class import after existing imports or the namespace declaration.
	 *
	 * Existing imports are left unchanged. Null is returned when the source
	 * cannot be parsed or a safe insertion offset cannot be determined.
	 */
	public function addImport(string $contents, string $fullyQualifiedClass): ?string {
		if ($this->hasImport($contents, $fullyQualifiedClass)) {
			return $contents;
		}

		$offset = $this->importInsertionOffset($contents);

		if ($offset === null) {
			return null;
		}

		$import = 'use ' . trim($fullyQualifiedClass, '\\') . ';';

		return substr($contents, 0, $offset) . $this->importSeparator($contents, $offset) . $import . substr($contents, $offset);
	}

	/**
	 * Insert a statement immediately before an exact standalone marker comment.
	 *
	 * The marker's indentation is reused so generated provider registrations
	 * follow the surrounding source formatting.
	 */
	public function insertBeforeLineComment(string $contents, string $comment, string $statement): ?string {
		$lineComment = $this->lineComment($contents, $comment);

		if ($lineComment === null) {
			return null;
		}

		return substr($contents, 0, $lineComment->lineStartOffset)
			. $lineComment->indent . $statement . "\n"
			. substr($contents, $lineComment->lineStartOffset);
	}

	/**
	 * Determine whether a matching `mergeArrayVar()` registration list can be edited safely.
	 *
	 * For example, this locates the array returned from
	 * `mergeArrayVar(DatabaseProvider::MIGRATIONS, static fn (C $c) => [...])`.
	 * Inline arrays are rejected because inserting a formatted line would be unsafe.
	 */
	public function canInsertIntoMergeArrayVar(string $contents, string $class, string $constant, ?string $beforeComment = null): bool {
		$target = $this->mergeArrayVarTarget($contents, $class, $constant);

		if ($target === null) {
			return false;
		}

		$insertion = $beforeComment === null ? null : $this->lineComment($contents, $beforeComment, $target->registrationList);
		$insertion ??= $this->arrayInsertion($contents, $target->registrationList);

		return $insertion !== null;
	}

	/**
	 * Return the container expression used by the first editable `mergeArrayVar()` callback.
	 *
	 * This returns expressions such as `$c` for callback registrations or
	 * `$this->container` when a direct array is supplied.
	 */
	public function mergeArrayVarContainerExpression(string $contents, string $class, string $constant): ?string {
		return $this->mergeArrayVarTarget($contents, $class, $constant)?->containerExpression;
	}

	/**
	 * Determine whether the provider registers a class with `$this->container->singleton()`.
	 *
	 * PHP names are resolved before comparison, so imported aliases and
	 * namespace-relative class references are recognized correctly.
	 */
	public function hasContainerSingleton(string $contents, string $fullyQualifiedClass): bool {
		$statements = $this->resolvedStatements($contents);

		if ($statements === null) {
			return false;
		}

		return $this->findNode(
			$statements,
			fn (Node $node): bool => $this->isContainerSingleton($node, $fullyQualifiedClass)
		) !== null;
	}

	/**
	 * Determine whether any matching `mergeArrayVar()` contribution resolves a class from its container.
	 *
	 * For example, this recognizes `$c->get(CreateReportsTable::class)` inside
	 * every contribution to `DatabaseProvider::MIGRATIONS`.
	 */
	public function mergeArrayVarContainsClass(string $contents, string $class, string $constant, string $fullyQualifiedClass): bool {
		foreach ($this->mergeArrayVarTargets($contents, $class, $constant) as $target) {
			foreach ($target->registrationList->items as $item) {
				if ($this->isContainerGet($item->value, $target->containerExpression, $fullyQualifiedClass)) {
					return true;
				}
			}
		}

		return false;
	}

	/**
	 * Insert a statement into the first safely editable matching `mergeArrayVar()` array.
	 *
	 * A marker inside the registration array is preferred when supplied;
	 * otherwise the statement is inserted immediately before the closing bracket.
	 */
	public function insertIntoMergeArrayVar(string $contents, string $class, string $constant, string $statement, ?string $beforeComment = null): ?string {
		$target = $this->mergeArrayVarTarget($contents, $class, $constant);

		if ($target === null) {
			return null;
		}

		$insertion = $beforeComment === null ? null : $this->lineComment($contents, $beforeComment, $target->registrationList);
		$insertion ??= $this->arrayInsertion($contents, $target->registrationList);

		if ($insertion === null) {
			return null;
		}

		return substr($contents, 0, $insertion->lineStartOffset)
			. $insertion->indent . $statement . "\n"
			. substr($contents, $insertion->lineStartOffset);
	}

	/**
	 * Collect top-level class imports and their effective aliases.
	 *
	 * Function and constant imports are excluded because they do not occupy the
	 * class symbol table used by generated declarations.
	 *
	 * @return list<array{class:string,alias:string}>
	 */
	private function imports(string $contents): array {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return [];
		}

		$imports = [];

		foreach ($this->topLevelStatements($statements) as $statement) {
			if ($statement instanceof Stmt\Use_) {
				$imports = array_merge($imports, $this->useImports($statement->uses, $statement->type));
			}

			if ($statement instanceof Stmt\GroupUse) {
				$imports = array_merge($imports, $this->groupUseImports($statement));
			}
		}

		return $imports;
	}

	/**
	 * Normalize a standard `use` statement into class and alias pairs.
	 *
	 * @param array<UseItem> $uses
	 *
	 * @return list<array{class:string,alias:string}>
	 */
	private function useImports(array $uses, int $type): array {
		if ($type !== Stmt\Use_::TYPE_NORMAL) {
			return [];
		}

		$imports = [];

		foreach ($uses as $use) {
			$imports[] = [
				'class' => $use->name->toString(),
				'alias' => $use->getAlias()->toString(),
			];
		}

		return $imports;
	}

	/**
	 * Normalize a grouped `use` statement into complete class and alias pairs.
	 *
	 * For example, `use Acme\{One, Two as Alias};` becomes two complete imports.
	 *
	 * @return list<array{class:string,alias:string}>
	 */
	private function groupUseImports(Stmt\GroupUse $groupUse): array {
		$imports = [];
		$prefix  = $groupUse->prefix->toString();

		foreach ($groupUse->uses as $use) {
			$type = $use->type === Stmt\Use_::TYPE_UNKNOWN ? $groupUse->type : $use->type;

			if ($type !== Stmt\Use_::TYPE_NORMAL) {
				continue;
			}

			$imports[] = [
				'class' => $prefix . '\\' . $use->name->toString(),
				'alias' => $use->getAlias()->toString(),
			];
		}

		return $imports;
	}

	/**
	 * Find where a new import belongs without disturbing namespace or declaration syntax.
	 *
	 * Imports are placed after the last existing import, then after the namespace,
	 * then after a strict-types declaration, or finally after the PHP opening tag.
	 */
	private function importInsertionOffset(string $contents): ?int {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return null;
		}

		$lastUse = null;

		foreach ($this->topLevelStatements($statements) as $statement) {
			if ($statement instanceof Stmt\Use_ || $statement instanceof Stmt\GroupUse) {
				$lastUse = $statement;
			}
		}

		if ($lastUse instanceof Node) {
			return $this->lineEndOffset($contents, $lastUse->getEndFilePos() + 1);
		}

		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Namespace_) {
				return $this->namespaceDeclarationEndOffset($contents, $statement);
			}
		}

		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Declare_) {
				return $statement->getEndFilePos() + 1;
			}
		}

		return $this->openingTagEndOffset($contents);
	}

	/**
	 * Find the byte offset immediately after a semicolon-style or braced namespace declaration.
	 */
	private function namespaceDeclarationEndOffset(string $contents, Stmt\Namespace_ $namespace): ?int {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if ($token->pos < $namespace->getStartFilePos()) {
				continue;
			}

			if ($token->id === ord(';') || $token->id === ord('{')) {
				return $token->getEndPos();
			}
		}

		return null;
	}

	/**
	 * Find the byte offset immediately after the PHP opening tag, or zero when none exists.
	 */
	private function openingTagEndOffset(string $contents): int {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if ($token->id === T_OPEN_TAG) {
				return $token->getEndPos();
			}
		}

		return 0;
	}

	/**
	 * Choose spacing for a new import based on whether an import block already exists.
	 */
	private function importSeparator(string $contents, int $offset): string {
		$before = substr($contents, 0, $offset);

		if (preg_match('/^use\s/m', $before) === 1) {
			return "\n";
		}

		return "\n\n";
	}

	/**
	 * Find an exact standalone line comment and preserve its source indentation.
	 *
	 * When `$within` is provided, only comments inside that syntax node are
	 * considered, preventing an unrelated marker elsewhere in the provider from matching.
	 */
	private function lineComment(string $contents, string $comment, ?Node $within = null): ?LineComment {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if (! $token->is(T_COMMENT) || trim($token->text) !== $comment) {
				continue;
			}

			if ($within !== null && ($token->pos < $within->getStartFilePos() || $token->pos > $within->getEndFilePos())) {
				continue;
			}

			$lineStartOffset = $this->lineStartOffset($contents, $token->pos);
			$indent          = substr($contents, $lineStartOffset, $token->pos - $lineStartOffset);

			if (trim($indent) !== '') {
				continue;
			}

			return new LineComment(
				indent: $indent,
				lineStartOffset: $lineStartOffset,
				commentStartOffset: $token->pos
			);
		}

		return null;
	}

	/**
	 * Return the first matching `mergeArrayVar()` target whose array has a safe line insertion point.
	 */
	private function mergeArrayVarTarget(string $contents, string $class, string $constant): ?MergeArrayVarTarget {
		foreach ($this->mergeArrayVarTargets($contents, $class, $constant) as $target) {
			if ($this->arrayInsertion($contents, $target->registrationList) !== null) {
				return $target;
			}
		}

		return null;
	}

	/**
	 * Collect every recognized `mergeArrayVar()` contribution for a class constant.
	 *
	 * For example, separate feature providers may each contribute to
	 * `DatabaseProvider::MIGRATIONS`; all contributions must be searched for duplicates.
	 *
	 * @return list<MergeArrayVarTarget>
	 */
	private function mergeArrayVarTargets(string $contents, string $class, string $constant): array {
		$statements = $this->resolvedStatements($contents);

		if ($statements === null) {
			return [];
		}

		$targets = [];
		$calls   = (new NodeFinder())->find(
			$statements,
			fn (Node $node): bool => $this->isMergeArrayVarCall($node, $class, $constant)
		);

		foreach ($calls as $call) {
			if (! $call instanceof Expr\MethodCall) {
				continue;
			}

			$target = $this->mergeArrayVarTargetFromCall($call);

			if ($target !== null) {
				$targets[] = $target;
			}
		}

		return $targets;
	}

	/**
	 * Determine whether a syntax node calls `$this->container->mergeArrayVar()` for the requested constant.
	 *
	 * Strauss-prefixed references are accepted when their resolved class ends
	 * with the requested Foundation class namespace.
	 */
	private function isMergeArrayVarCall(Node $node, string $class, string $constant): bool {
		if (! $node instanceof Expr\MethodCall || ! $node->name instanceof Node\Identifier || $node->name->toString() !== 'mergeArrayVar') {
			return false;
		}

		if (! $this->isThisContainer($node->var)) {
			return false;
		}

		$firstArgument = $node->args[0]->value ?? null;

		if (! $firstArgument instanceof Expr\ClassConstFetch || ! $firstArgument->class instanceof Node\Name || ! $firstArgument->name instanceof Node\Identifier) {
			return false;
		}

		if ($firstArgument->name->toString() !== $constant) {
			return false;
		}

		return $this->isClassReference($firstArgument->class, $class, true);
	}

	/**
	 * Determine whether a syntax node is a singleton registration for the requested class.
	 */
	private function isContainerSingleton(Node $node, string $class): bool {
		if (! $node instanceof Expr\MethodCall || ! $node->name instanceof Node\Identifier || $node->name->toString() !== 'singleton') {
			return false;
		}

		if (! $this->isThisContainer($node->var)) {
			return false;
		}

		$argument = $node->args[0]->value ?? null;

		return $argument instanceof Expr\ClassConstFetch
			&& $argument->class instanceof Node\Name
			&& $argument->name instanceof Node\Identifier
			&& $argument->name->toString() === 'class'
			&& $this->isClassReference($argument->class, $class);
	}

	/**
	 * Determine whether an array item resolves the requested class from the callback container.
	 *
	 * The receiver must match the callback parameter, such as `$c` in
	 * `static fn (C $c): array => [$c->get(Service::class)]`.
	 */
	private function isContainerGet(Node $node, string $containerExpression, string $class): bool {
		if (! $node instanceof Expr\MethodCall || ! $node->name instanceof Node\Identifier || $node->name->toString() !== 'get') {
			return false;
		}

		if (! $this->matchesContainerExpression($node->var, $containerExpression)) {
			return false;
		}

		$argument = $node->args[0]->value ?? null;

		return $argument instanceof Expr\ClassConstFetch
			&& $argument->class instanceof Node\Name
			&& $argument->name instanceof Node\Identifier
			&& $argument->name->toString() === 'class'
			&& $this->isClassReference($argument->class, $class);
	}

	/**
	 * Determine whether a node represents the expected callback variable or provider container property.
	 */
	private function matchesContainerExpression(Node $node, string $containerExpression): bool {
		if ($containerExpression === '$this->container') {
			return $this->isThisContainer($node);
		}

		return $node instanceof Expr\Variable
			&& is_string($node->name)
			&& '$' . $node->name === $containerExpression;
	}

	/**
	 * Compare a PHP name using the fully resolved name attached by PHP-Parser.
	 */
	private function isClassReference(Node\Name $name, string $class, bool $allowPrefixed = false): bool {
		$resolved = $name->getAttribute('resolvedName') ?? $name->getAttribute('namespacedName');

		return $resolved instanceof Node\Name
			&& $this->classMatches($resolved->toString(), $class, $allowPrefixed);
	}

	/**
	 * Compare class names case-insensitively, optionally allowing a namespace prefix.
	 *
	 * Prefix matching supports rewritten references such as
	 * `Acme\Prefixed\StellarWP\Foundation\Database\DatabaseProvider`.
	 */
	private function classMatches(string $reference, string $class, bool $allowPrefixed = false): bool {
		$reference = trim($reference, '\\');
		$class     = trim($class, '\\');

		if (strcasecmp($reference, $class) === 0) {
			return true;
		}

		return $allowPrefixed
			&& strlen($reference) > strlen($class)
			&& strcasecmp(substr($reference, -strlen($class) - 1), '\\' . $class) === 0;
	}

	/**
	 * Determine whether a node is exactly the provider's `$this->container` property.
	 */
	private function isThisContainer(Node $node): bool {
		return $node instanceof Expr\PropertyFetch
			&& $node->var instanceof Expr\Variable
			&& $node->var->name === 'this'
			&& $node->name instanceof Node\Identifier
			&& $node->name->toString() === 'container';
	}

	/**
	 * Extract the editable registration array and its container expression from a merge call.
	 *
	 * Supported values are a direct array, an arrow function returning an array,
	 * or a closure with an explicit array return statement.
	 */
	private function mergeArrayVarTargetFromCall(Expr\MethodCall $call): ?MergeArrayVarTarget {
		$callback = $call->args[1]->value ?? null;

		if ($callback instanceof Expr\Array_) {
			return new MergeArrayVarTarget(
				registrationList: $callback,
				containerExpression: '$this->container'
			);
		}

		if ($callback instanceof Expr\ArrowFunction && $callback->expr instanceof Expr\Array_) {
			$containerExpression = $this->callbackContainerExpression($callback);

			if ($containerExpression === null) {
				return null;
			}

			return new MergeArrayVarTarget(
				registrationList: $callback->expr,
				containerExpression: $containerExpression
			);
		}

		if (! $callback instanceof Expr\Closure) {
			return null;
		}

		foreach ($callback->stmts as $statement) {
			if ($statement instanceof Stmt\Return_ && $statement->expr instanceof Expr\Array_) {
				$containerExpression = $this->callbackContainerExpression($callback);

				if ($containerExpression === null) {
					return null;
				}

				return new MergeArrayVarTarget(
					registrationList: $statement->expr,
					containerExpression: $containerExpression
				);
			}
		}

		return null;
	}

	/**
	 * Return the first callback parameter as a source expression such as `$c`.
	 */
	private function callbackContainerExpression(Expr\Closure|Expr\ArrowFunction $callback): ?string {
		$parameter = $callback->params[0] ?? null;

		if ($parameter === null || ! $parameter->var instanceof Expr\Variable || ! is_string($parameter->var->name)) {
			return null;
		}

		return '$' . $parameter->var->name;
	}

	/**
	 * Calculate a formatting-preserving insertion before a multiline array's closing bracket.
	 *
	 * Single-line arrays return null because inserting a line without reprinting the
	 * complete syntax tree could corrupt formatting or comments.
	 */
	private function arrayInsertion(string $contents, Expr\Array_ $array): ?LineInsertion {
		$indent = null;

		if ($array->items !== []) {
			$firstItem       = $array->items[0];
			$lineStartOffset = $this->lineStartOffset($contents, $firstItem->getStartFilePos());
			$firstItemIndent = substr($contents, $lineStartOffset, $firstItem->getStartFilePos() - $lineStartOffset);

			if (trim($firstItemIndent) === '') {
				$indent = $firstItemIndent;
			}
		}

		$closingOffset   = $array->getEndFilePos();
		$lineStartOffset = $this->lineStartOffset($contents, $closingOffset);
		$closingIndent   = substr($contents, $lineStartOffset, $closingOffset - $lineStartOffset);

		if (trim($closingIndent) !== '') {
			return null;
		}

		return new LineInsertion(
			lineStartOffset: $lineStartOffset,
			indent: $indent ?? $this->childIndent($closingIndent)
		);
	}

	/**
	 * Add one indentation level while preserving the surrounding tab or space style.
	 */
	private function childIndent(string $indent): string {
		if ($indent === '' || str_contains($indent, "\t")) {
			return $indent . "\t";
		}

		return $indent . '    ';
	}

	/**
	 * Search statements depth-first and return the first node accepted by a predicate.
	 *
	 * @param array<Node\Stmt>     $statements
	 * @param callable(Node): bool $predicate
	 */
	private function findNode(array $statements, callable $predicate): ?Node {
		foreach ($statements as $statement) {
			$match = $this->findMatchingNode($statement, $predicate);

			if ($match instanceof Node) {
				return $match;
			}
		}

		return null;
	}

	/**
	 * Search one syntax node and its descendants depth-first.
	 *
	 * @param callable(Node): bool $predicate
	 */
	private function findMatchingNode(Node $node, callable $predicate): ?Node {
		if ($predicate($node)) {
			return $node;
		}

		foreach ($node->getSubNodeNames() as $name) {
			$value = $node->{$name};

			if ($value instanceof Node) {
				$match = $this->findMatchingNode($value, $predicate);

				if ($match instanceof Node) {
					return $match;
				}
			}

			if (is_array($value)) {
				foreach ($value as $item) {
					if (! $item instanceof Node) {
						continue;
					}

					$match = $this->findMatchingNode($item, $predicate);

					if ($match instanceof Node) {
						return $match;
					}
				}
			}
		}

		return null;
	}

	/**
	 * Return the byte offset of the first character on the line containing an offset.
	 */
	private function lineStartOffset(string $contents, int $offset): int {
		$previousNewline = strrpos(substr($contents, 0, $offset), "\n");

		if ($previousNewline === false) {
			return 0;
		}

		return $previousNewline + 1;
	}

	/**
	 * Return the byte offset of the newline ending a line, or the end of the source.
	 */
	private function lineEndOffset(string $contents, int $offset): int {
		$nextNewline = strpos($contents, "\n", $offset);

		if ($nextNewline === false) {
			return strlen($contents);
		}

		return $nextNewline;
	}

	/**
	 * Return statements inside the first namespace, or the original root statements.
	 *
	 * Generator targets use one namespace per file, so imports and declarations are
	 * inspected only within that file-level namespace.
	 *
	 * @param array<Node\Stmt> $statements
	 *
	 * @return array<Node\Stmt>
	 */
	private function topLevelStatements(array $statements): array {
		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Namespace_) {
				return $statement->stmts;
			}
		}

		return $statements;
	}

	/**
	 * Parse source while converting PHP-Parser syntax failures to null.
	 *
	 * @return array<Node\Stmt>|null
	 */
	private function parse(string $contents): ?array {
		try {
			return $this->parserFactory->createForNewestSupportedVersion()->parse($contents);
		} catch (Error) {
			return null;
		}
	}

	/**
	 * Parse source and attach PHP-resolved names without replacing original nodes.
	 *
	 * Keeping original nodes preserves source offsets for edits while resolvedName and
	 * namespacedName attributes provide PHP-accurate comparisons for aliases and prefixes.
	 *
	 * @return array<Node\Stmt>|null
	 */
	private function resolvedStatements(string $contents): ?array {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return null;
		}

		$traverser = new NodeTraverser();
		$traverser->addVisitor(new NameResolver(null, ['replaceNodes' => false]));

		try {
			return array_values(array_filter(
				$traverser->traverse($statements),
				static fn (Node $node): bool => $node instanceof Stmt
			));
		} catch (Error) {
			return null;
		}
	}
}
