<?php declare(strict_types=1);

namespace StellarWP\Foundation\Cli\Generation\Php;

use PhpParser\Error;
use PhpParser\Lexer;
use PhpParser\Node;
use PhpParser\Node\Expr;
use PhpParser\Node\Stmt;
use PhpParser\Node\UseItem;
use PhpParser\ParserFactory;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\LineComment;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\LineInsertion;
use StellarWP\Foundation\Cli\Generation\Php\ValueObjects\MergeArrayVarTarget;

/**
 * Performs small, parser-aware edits to PHP source files generated by Foundation.
 */
final readonly class PhpSourceEditor
{
	public function __construct(
		private ParserFactory $parserFactory,
		private Lexer $lexer
	) {
	}

	public function canParse(string $contents): bool {
		return $this->parse($contents) !== null;
	}

	public function hasImport(string $contents, string $fullyQualifiedClass): bool {
		$target = trim($fullyQualifiedClass, '\\');
		$alias  = basename(str_replace('\\', '/', $target));

		foreach ($this->imports($contents) as $import) {
			if ($import['class'] === $target && $import['alias'] === $alias) {
				return true;
			}
		}

		return false;
	}

	public function hasImportShortNameCollision(string $contents, string $class, string $fullyQualifiedClass): bool {
		$target = trim($fullyQualifiedClass, '\\');

		foreach ($this->imports($contents) as $import) {
			if ($import['alias'] === $class && $import['class'] !== $target) {
				return true;
			}
		}

		return false;
	}

	public function hasLineComment(string $contents, string $comment): bool {
		return $this->lineComment($contents, $comment) !== null;
	}

	public function addImport(string $contents, string $fullyQualifiedClass): ?string {
		if ($this->hasImport($contents, $fullyQualifiedClass)) {
			return $contents;
		}

		$offset = $this->importInsertionOffset($contents);

		if ($offset === null) {
			return null;
		}

		$import = 'use ' . trim($fullyQualifiedClass, '\\') . ';';

		return substr($contents, 0, $offset) . $this->importSeparator($contents, $offset) . $import . substr($contents, $offset);
	}

	public function insertBeforeLineComment(string $contents, string $comment, string $statement): ?string {
		$lineComment = $this->lineComment($contents, $comment);

		if ($lineComment === null) {
			return null;
		}

		return substr($contents, 0, $lineComment->lineStartOffset)
			. $lineComment->indent . $statement . "\n"
			. substr($contents, $lineComment->lineStartOffset);
	}

	public function canInsertIntoMergeArrayVar(string $contents, string $class, string $constant, ?string $beforeComment = null): bool {
		$target = $this->mergeArrayVarTarget($contents, $class, $constant);

		if ($target === null) {
			return false;
		}

		$insertion = $beforeComment === null ? null : $this->lineComment($contents, $beforeComment, $target->registrationList);
		$insertion ??= $this->arrayInsertion($contents, $target->registrationList);

		return $insertion !== null;
	}

	public function mergeArrayVarContainerExpression(string $contents, string $class, string $constant): ?string {
		return $this->mergeArrayVarTarget($contents, $class, $constant)?->containerExpression;
	}

	public function insertIntoMergeArrayVar(string $contents, string $class, string $constant, string $statement, ?string $beforeComment = null): ?string {
		$target = $this->mergeArrayVarTarget($contents, $class, $constant);

		if ($target === null) {
			return null;
		}

		$insertion = $beforeComment === null ? null : $this->lineComment($contents, $beforeComment, $target->registrationList);
		$insertion ??= $this->arrayInsertion($contents, $target->registrationList);

		if ($insertion === null) {
			return null;
		}

		return substr($contents, 0, $insertion->lineStartOffset)
			. $insertion->indent . $statement . "\n"
			. substr($contents, $insertion->lineStartOffset);
	}

	/**
	 * @return list<array{class:string,alias:string}>
	 */
	private function imports(string $contents): array {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return [];
		}

		$imports = [];

		foreach ($this->topLevelStatements($statements) as $statement) {
			if ($statement instanceof Stmt\Use_) {
				$imports = array_merge($imports, $this->useImports($statement->uses, $statement->type));
			}

			if ($statement instanceof Stmt\GroupUse) {
				$imports = array_merge($imports, $this->groupUseImports($statement));
			}
		}

		return $imports;
	}

	/**
	 * @param array<UseItem> $uses
	 *
	 * @return list<array{class:string,alias:string}>
	 */
	private function useImports(array $uses, int $type): array {
		if ($type !== Stmt\Use_::TYPE_NORMAL) {
			return [];
		}

		$imports = [];

		foreach ($uses as $use) {
			$imports[] = [
				'class' => $use->name->toString(),
				'alias' => $use->getAlias()->toString(),
			];
		}

		return $imports;
	}

	/**
	 * @return list<array{class:string,alias:string}>
	 */
	private function groupUseImports(Stmt\GroupUse $groupUse): array {
		$imports = [];
		$prefix  = $groupUse->prefix->toString();

		foreach ($groupUse->uses as $use) {
			$type = $use->type === Stmt\Use_::TYPE_UNKNOWN ? $groupUse->type : $use->type;

			if ($type !== Stmt\Use_::TYPE_NORMAL) {
				continue;
			}

			$imports[] = [
				'class' => $prefix . '\\' . $use->name->toString(),
				'alias' => $use->getAlias()->toString(),
			];
		}

		return $imports;
	}

	private function importInsertionOffset(string $contents): ?int {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return null;
		}

		$lastUse = null;

		foreach ($this->topLevelStatements($statements) as $statement) {
			if ($statement instanceof Stmt\Use_ || $statement instanceof Stmt\GroupUse) {
				$lastUse = $statement;
			}
		}

		if ($lastUse instanceof Node) {
			return $this->lineEndOffset($contents, $lastUse->getEndFilePos() + 1);
		}

		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Namespace_) {
				return $this->namespaceDeclarationEndOffset($contents, $statement);
			}
		}

		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Declare_) {
				return $statement->getEndFilePos() + 1;
			}
		}

		return $this->openingTagEndOffset($contents);
	}

	private function namespaceDeclarationEndOffset(string $contents, Stmt\Namespace_ $namespace): ?int {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if ($token->pos < $namespace->getStartFilePos()) {
				continue;
			}

			if ($token->id === ord(';') || $token->id === ord('{')) {
				return $token->getEndPos();
			}
		}

		return null;
	}

	private function openingTagEndOffset(string $contents): int {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if ($token->id === T_OPEN_TAG) {
				return $token->getEndPos();
			}
		}

		return 0;
	}

	private function importSeparator(string $contents, int $offset): string {
		$before = substr($contents, 0, $offset);

		if (preg_match('/^use\s/m', $before) === 1) {
			return "\n";
		}

		return "\n\n";
	}

	private function lineComment(string $contents, string $comment, ?Node $within = null): ?LineComment {
		foreach ($this->lexer->tokenize($contents) as $token) {
			if (! $token->is(T_COMMENT) || trim($token->text) !== $comment) {
				continue;
			}

			if ($within !== null && ($token->pos < $within->getStartFilePos() || $token->pos > $within->getEndFilePos())) {
				continue;
			}

			$lineStartOffset = $this->lineStartOffset($contents, $token->pos);
			$indent          = substr($contents, $lineStartOffset, $token->pos - $lineStartOffset);

			if (trim($indent) !== '') {
				continue;
			}

			return new LineComment(
				indent: $indent,
				lineStartOffset: $lineStartOffset,
				commentStartOffset: $token->pos
			);
		}

		return null;
	}

	private function mergeArrayVarTarget(string $contents, string $class, string $constant): ?MergeArrayVarTarget {
		$statements = $this->parse($contents);

		if ($statements === null) {
			return null;
		}

		$aliases = $this->classAliases($contents, $class);
		$call    = $this->findNode($statements, fn (Node $node): bool => $this->isMergeArrayVarCall($node, $class, $constant, $aliases));

		if (! $call instanceof Expr\MethodCall) {
			return null;
		}

		return $this->mergeArrayVarTargetFromCall($call);
	}

	/**
	 * @return list<string>
	 */
	private function classAliases(string $contents, string $class): array {
		$class   = trim($class, '\\');
		$aliases = [];

		foreach ($this->imports($contents) as $import) {
			if ($import['class'] === $class || str_ends_with($import['class'], '\\' . $class)) {
				$aliases[] = $import['alias'];
			}
		}

		return $aliases;
	}

	/**
	 * @param list<string> $aliases
	 */
	private function isMergeArrayVarCall(Node $node, string $class, string $constant, array $aliases): bool {
		if (! $node instanceof Expr\MethodCall || ! $node->name instanceof Node\Identifier || $node->name->toString() !== 'mergeArrayVar') {
			return false;
		}

		if (! $this->isThisContainer($node->var)) {
			return false;
		}

		$firstArgument = $node->args[0]->value ?? null;

		if (! $firstArgument instanceof Expr\ClassConstFetch || ! $firstArgument->class instanceof Node\Name || ! $firstArgument->name instanceof Node\Identifier) {
			return false;
		}

		if ($firstArgument->name->toString() !== $constant) {
			return false;
		}

		$referencedClass = $firstArgument->class->toString();

		if (str_contains($referencedClass, '\\')) {
			$referencedClass = trim($referencedClass, '\\');

			return $referencedClass === $class || str_ends_with($referencedClass, '\\' . $class);
		}

		return in_array($referencedClass, $aliases, true);
	}

	private function isThisContainer(Node $node): bool {
		return $node instanceof Expr\PropertyFetch
			&& $node->var instanceof Expr\Variable
			&& $node->var->name === 'this'
			&& $node->name instanceof Node\Identifier
			&& $node->name->toString() === 'container';
	}

	private function mergeArrayVarTargetFromCall(Expr\MethodCall $call): ?MergeArrayVarTarget {
		$callback = $call->args[1]->value ?? null;

		if ($callback instanceof Expr\Array_) {
			return new MergeArrayVarTarget(
				registrationList: $callback,
				containerExpression: '$this->container'
			);
		}

		if ($callback instanceof Expr\ArrowFunction && $callback->expr instanceof Expr\Array_) {
			$containerExpression = $this->callbackContainerExpression($callback);

			if ($containerExpression === null) {
				return null;
			}

			return new MergeArrayVarTarget(
				registrationList: $callback->expr,
				containerExpression: $containerExpression
			);
		}

		if (! $callback instanceof Expr\Closure) {
			return null;
		}

		foreach ($callback->stmts as $statement) {
			if ($statement instanceof Stmt\Return_ && $statement->expr instanceof Expr\Array_) {
				$containerExpression = $this->callbackContainerExpression($callback);

				if ($containerExpression === null) {
					return null;
				}

				return new MergeArrayVarTarget(
					registrationList: $statement->expr,
					containerExpression: $containerExpression
				);
			}
		}

		return null;
	}

	private function callbackContainerExpression(Expr\Closure|Expr\ArrowFunction $callback): ?string {
		$parameter = $callback->params[0] ?? null;

		if ($parameter === null || ! $parameter->var instanceof Expr\Variable || ! is_string($parameter->var->name)) {
			return null;
		}

		return '$' . $parameter->var->name;
	}

	private function arrayInsertion(string $contents, Expr\Array_ $array): ?LineInsertion {
		$indent = null;

		if ($array->items !== []) {
			$firstItem       = $array->items[0];
			$lineStartOffset = $this->lineStartOffset($contents, $firstItem->getStartFilePos());
			$firstItemIndent = substr($contents, $lineStartOffset, $firstItem->getStartFilePos() - $lineStartOffset);

			if (trim($firstItemIndent) === '') {
				$indent = $firstItemIndent;
			}
		}

		$closingOffset   = $array->getEndFilePos();
		$lineStartOffset = $this->lineStartOffset($contents, $closingOffset);
		$closingIndent   = substr($contents, $lineStartOffset, $closingOffset - $lineStartOffset);

		if (trim($closingIndent) !== '') {
			return null;
		}

		return new LineInsertion(
			lineStartOffset: $lineStartOffset,
			indent: $indent ?? $this->childIndent($closingIndent)
		);
	}

	private function childIndent(string $indent): string {
		if ($indent === '' || str_contains($indent, "\t")) {
			return $indent . "\t";
		}

		return $indent . '    ';
	}

	/**
	 * @param array<Node\Stmt>     $statements
	 * @param callable(Node): bool $predicate
	 */
	private function findNode(array $statements, callable $predicate): ?Node {
		foreach ($statements as $statement) {
			$match = $this->findMatchingNode($statement, $predicate);

			if ($match instanceof Node) {
				return $match;
			}
		}

		return null;
	}

	/**
	 * @param callable(Node): bool $predicate
	 */
	private function findMatchingNode(Node $node, callable $predicate): ?Node {
		if ($predicate($node)) {
			return $node;
		}

		foreach ($node->getSubNodeNames() as $name) {
			$value = $node->{$name};

			if ($value instanceof Node) {
				$match = $this->findMatchingNode($value, $predicate);

				if ($match instanceof Node) {
					return $match;
				}
			}

			if (is_array($value)) {
				foreach ($value as $item) {
					if (! $item instanceof Node) {
						continue;
					}

					$match = $this->findMatchingNode($item, $predicate);

					if ($match instanceof Node) {
						return $match;
					}
				}
			}
		}

		return null;
	}

	private function lineStartOffset(string $contents, int $offset): int {
		$previousNewline = strrpos(substr($contents, 0, $offset), "\n");

		if ($previousNewline === false) {
			return 0;
		}

		return $previousNewline + 1;
	}

	private function lineEndOffset(string $contents, int $offset): int {
		$nextNewline = strpos($contents, "\n", $offset);

		if ($nextNewline === false) {
			return strlen($contents);
		}

		return $nextNewline;
	}

	/**
	 * @param array<Node\Stmt> $statements
	 *
	 * @return array<Node\Stmt>
	 */
	private function topLevelStatements(array $statements): array {
		foreach ($statements as $statement) {
			if ($statement instanceof Stmt\Namespace_) {
				return $statement->stmts;
			}
		}

		return $statements;
	}

	/**
	 * @return array<Node\Stmt>|null
	 */
	private function parse(string $contents): ?array {
		try {
			return $this->parserFactory->createForNewestSupportedVersion()->parse($contents);
		} catch (Error) {
			return null;
		}
	}
}
