# Pushes releases out to stellarwp/prophecy-* git sub-repos.
name: Split Monorepo Packages and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  list-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Dynamically build an array of JSON objects that each contain "name" and "directory" properties.
      - name: Set repo matrix
        id: set-matrix
        run: echo "matrix=$(./.github/bin/repo-map.sh)" >> "$GITHUB_OUTPUT"

  split:
    needs: list-repos
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.list-repos.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # no tag
      - name: Split with no tag
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        uses: moderntribe/monorepo-split-github-action@4.0.2
        with:
          package_directory: 'src/${{ matrix.package.directory }}'
          repository_organization: 'stellarwp'
          repository_name: '${{ matrix.package.name }}'

          # ↓ the user signed under the split commit
          user_name: "StellarWP GitHub Action"
          user_email: "action@github.com"

      # with tag
      - name: With regular tag
        if: ${{ startsWith(github.ref, 'refs/tags/')}}
        uses: moderntribe/monorepo-split-github-action@4.0.2
        with:
          tag: "${GITHUB_REF#refs/tags/}"

          package_directory: 'src/${{ matrix.package.directory }}'
          repository_organization: 'stellarwp'
          repository_name: '${{ matrix.package.name }}'

          # ↓ the user signed under the split commit
          user_name: "StellarWP GitHub Action"
          user_email: "action@github.com"
